### ISSUE TITLE
When using one of optional filters, only english reviews get scrapped

### ISSUE THREAD

**Issue by LukasLamacz** [epctex/tripadvisor-reviews-scraper#1]
When I run your scrapper on APIFY without any filters like Maximum number of reviews or List end page, scrapper returns all reviews, but when we are using them, scrapper only returns reviews that were posted in English. Is it something you can fix?

Actor run:
https://console.apify.com/organization/b56n9xw6cEZ274ScA/actors/vjPBUmIq9Dzcip2XI/runs/5NgkLLrHmzPMVmsoh#input

**Comment by LukasLamacz** [comment]
I think it might be due to sorting. It seems that reviews are sorted first by language and then by published date. So in case there are most recent reviews posted in Italian i.e. they don't get scrapped.

**Comment by tugkan** [comment]
Hey there!

Thank you very much for reaching out. We just deployed a new version where you can define `languages` and `review` filters. That deployment also fixed the problem that you mentioned.

Best
